"""set ondelete CASCADE for comments.issue_id foreign key

Revision ID: 07caf539115b
Revises: f9d63a3f63c7
Create Date: 2025-07-20 17:29:09.398420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07caf539115b'
down_revision: Union[str, Sequence[str], None] = 'f9d63a3f63c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_issue_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'issues', ['issue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_issue_id_fkey'), 'comments', 'issues', ['issue_id'], ['id'])
    # ### end Alembic commands ###
