"""create user_activities table

Revision ID: e1bbc3d2ba7e
Revises: 07e3a187f499
Create Date: 2025-07-20 15:58:58.939753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bbc3d2ba7e'
down_revision: Union[str, Sequence[str], None] = '07e3a187f499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('LOGIN', 'LOGOUT', 'CREATE_ISSUE', 'UPDATE_ISSUE', 'DELETE_ISSUE', 'CREATE_COMMENT', 'UPDATE_COMMENT', 'DELETE_COMMENT', 'UPDATE_PROFILE', 'CHANGE_ROLE', 'CHANGE_STATUS', name='activity_type'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_id'), 'user_activities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activities_id'), table_name='user_activities')
    op.drop_table('user_activities')
    # ### end Alembic commands ###
